import {
  Field,
  Float,
  GraphQLISODateTime,
  ID,
  Int,
  ObjectType,
} from "@nestjs/graphql";
import { Types } from "mongoose";

import { ProductReviewVisibility, UserRole } from "../../../../enums";
import { PaginationCursorResponse } from "../../../../common/pagination/response";
import { UserMinimalGqlResponse } from "../../../user/graphql/responses/common";

@ObjectType()
export class ProductReviewModerationGqlResponse {
  @Field(() => ProductReviewVisibility, {
    description: "Moderation visibility for this content",
  })
  visibility: ProductReviewVisibility;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the content was hidden",
  })
  hiddenAt?: Date;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that hid the content",
  })
  hiddenByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that hid the content",
  })
  hiddenByUser?: UserMinimalGqlResponse;

  @Field({
    nullable: true,
    description: "Internal moderation note",
  })
  hiddenReason?: string;
}

@ObjectType()
export class ProductReviewRatingGqlResponse {
  @Field(() => Int, { description: "Star rating from 1 to 5" })
  stars: number;

  @Field({ nullable: true, description: "Optional review comment" })
  comment?: string;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the rating was first submitted",
  })
  ratedAt: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the rating was last updated",
  })
  updatedAt?: Date;

  @Field(() => ProductReviewModerationGqlResponse, {
    description: "Rating moderation metadata",
  })
  moderation: ProductReviewModerationGqlResponse;
}

@ObjectType()
export class ProductReviewMessageGqlResponse {
  @Field({ description: "Stable message key generated by the database" })
  key: string;

  @Field({ description: "Message body" })
  body: string;

  @Field(() => ID, { description: "Sender user ID" })
  senderUserId: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal sender user information",
  })
  senderUser?: UserMinimalGqlResponse;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the message was sent",
  })
  sentAt: Date;

  @Field(() => ProductReviewModerationGqlResponse, {
    description: "Message moderation metadata",
  })
  moderation: ProductReviewModerationGqlResponse;
}

@ObjectType()
export class ProductReviewUserSnapshotGqlResponse {
  @Field({ description: "Stored full name snapshot" })
  fullName: string;

  @Field({ description: "Stored username snapshot" })
  username: string;

  @Field(() => ID, {
    nullable: true,
    description: "Stored avatar file ID snapshot",
  })
  avatarFileId?: Types.ObjectId;
}

@ObjectType()
export class ProductReviewProductSnapshotGqlResponse {
  @Field({ description: "Stored product title snapshot" })
  title: string;
}

@ObjectType()
export class ProductReviewListGqlResponse {
  @Field(() => ID, { description: "Product review thread ID" })
  id: Types.ObjectId;

  @Field(() => ID, { description: "Review owner user ID" })
  userId: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal review owner information",
  })
  user?: UserMinimalGqlResponse;

  @Field(() => ID, { description: "Product ID" })
  productId: Types.ObjectId;

  @Field(() => ID, {
    nullable: true,
    description:
      "Linked user product enrollment ID, when the reviewer purchased the product",
  })
  userProductId?: Types.ObjectId;

  @Field(() => ProductReviewUserSnapshotGqlResponse, {
    description: "Stored review owner snapshot",
  })
  userSnapshot: ProductReviewUserSnapshotGqlResponse;

  @Field(() => ProductReviewProductSnapshotGqlResponse, {
    description: "Stored product snapshot",
  })
  productSnapshot: ProductReviewProductSnapshotGqlResponse;

  @Field(() => ProductReviewModerationGqlResponse, {
    description: "Review thread moderation metadata",
  })
  moderation: ProductReviewModerationGqlResponse;

  @Field(() => ProductReviewRatingGqlResponse, {
    nullable: true,
    description: "Product rating, if submitted",
  })
  rating?: ProductReviewRatingGqlResponse;

  @Field(() => [ProductReviewMessageGqlResponse], {
    description: "Full Q&A message thread",
  })
  messages: ProductReviewMessageGqlResponse[];

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the review thread was created",
  })
  createdAt?: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the review thread was last updated",
  })
  updatedAt?: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the review thread was soft deleted",
  })
  deletedAt?: Date;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that created the review thread",
  })
  createdByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that created the review thread",
  })
  createdByUser?: UserMinimalGqlResponse;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that last updated the review thread",
  })
  updatedByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that last updated the review thread",
  })
  updatedByUser?: UserMinimalGqlResponse;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that soft deleted the review thread",
  })
  deletedByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that soft deleted the review thread",
  })
  deletedByUser?: UserMinimalGqlResponse;
}

@ObjectType()
export class ProductReviewRatingDistributionGqlResponse {
  @Field(() => Int, { description: "Star value from 1 to 5" })
  stars: number;

  @Field(() => Int, { description: "Number of ratings with this star value" })
  count: number;

  @Field(() => Int, {
    description: "Share of eligible ratings, rounded to a percent",
  })
  percentage: number;
}

@ObjectType()
export class ProductReviewRatingSummaryGqlResponse {
  @Field(() => Float, {
    nullable: true,
    description: "Average star rating across eligible reviews",
  })
  averageRating: number | null;

  @Field(() => Int, {
    description: "Number of eligible ratings included in the summary",
  })
  ratedCount: number;

  @Field(() => [ProductReviewRatingDistributionGqlResponse], {
    description: "Distribution of eligible ratings by star value",
  })
  distribution: ProductReviewRatingDistributionGqlResponse[];
}

@ObjectType()
export class ProductReviewPendingModerationStatsGqlResponse {
  @Field(() => Int, {
    description:
      "Number of distinct users with at least one pending moderation item for this product",
  })
  userCount: number;

  @Field(() => Int, {
    description:
      "Total pending moderation items (thread, rating, and messages) for this product",
  })
  reviewCount: number;
}

@ObjectType()
export class ProductReviewListPaginatedCursorGqlResponse {
  @Field(() => [ProductReviewListGqlResponse], {
    description: "Full product review list for SUPER_ADMIN",
  })
  items: ProductReviewListGqlResponse[];

  @Field(() => PaginationCursorResponse, {
    description: "Pagination metadata",
  })
  pagination: PaginationCursorResponse;

  @Field(() => ProductReviewRatingSummaryGqlResponse, {
    description:
      "Aggregated rating summary excluding hidden reviews and hidden ratings",
  })
  summary: ProductReviewRatingSummaryGqlResponse;

  @Field(() => ProductReviewPendingModerationStatsGqlResponse, {
    nullable: true,
    description:
      "Pending moderation counts when productReviewList is filtered by productId",
  })
  pendingModerationStats?: ProductReviewPendingModerationStatsGqlResponse;
}
