import {
  Field,
  GraphQLISODateTime,
  ID,
  Int,
  ObjectType,
} from "@nestjs/graphql";
import { Types } from "mongoose";

import { PaginationCursorResponse } from "../../../../common/pagination/response";
import { ProductReviewRatingSummaryGqlResponse } from "./product-review-list.gql.response";

@ObjectType()
export class UserProductReviewAuthorGqlResponse {
  @Field({ description: "Review author's first name from the user profile" })
  firstName: string;
}

@ObjectType()
export class UserProductReviewRatingGqlResponse {
  @Field(() => Int, { description: "Star rating from 1 to 5" })
  stars: number;

  @Field({ nullable: true, description: "Optional review comment" })
  comment?: string;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the rating was first submitted",
  })
  ratedAt: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the rating was last updated",
  })
  updatedAt?: Date;
}

@ObjectType()
export class UserProductReviewMessageSenderGqlResponse {
  @Field({ description: "Message sender first name from the user profile" })
  firstName: string;

  @Field({
    description:
      "Whether the message was sent by support staff rather than the review author",
  })
  isSupport: boolean;
}

@ObjectType()
export class UserProductReviewMessageGqlResponse {
  @Field({ description: "Stable message key generated by the database" })
  key: string;

  @Field({ description: "Message body" })
  body: string;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the message was sent",
  })
  sentAt: Date;

  @Field(() => UserProductReviewMessageSenderGqlResponse, {
    description: "Sanitized sender information",
  })
  sender: UserProductReviewMessageSenderGqlResponse;
}

@ObjectType()
export class UserProductReviewListGqlResponse {
  @Field(() => ID, { description: "Product review thread ID" })
  id: Types.ObjectId;

  @Field({
    description: "Whether this review thread belongs to the current user",
  })
  isMine: boolean;

  @Field(() => UserProductReviewAuthorGqlResponse, {
    description: "Sanitized review author information",
  })
  author: UserProductReviewAuthorGqlResponse;

  @Field(() => UserProductReviewRatingGqlResponse, {
    nullable: true,
    description: "Rating visible when its moderation visibility is PUBLIC",
  })
  rating?: UserProductReviewRatingGqlResponse;

  @Field(() => [UserProductReviewMessageGqlResponse], {
    description:
      "Public follow-up comments and support messages with PUBLIC moderation",
  })
  messages: UserProductReviewMessageGqlResponse[];

  @Field({
    description:
      "Whether the current user is blocked from submitting updates because the review thread is hidden",
    defaultValue: false,
  })
  isSubmissionBlocked: boolean;

  @Field({
    description:
      "Whether the current user's rating exists but is hidden from their view",
    defaultValue: false,
  })
  isRatingHidden: boolean;
}

@ObjectType()
export class UserProductReviewListPaginatedCursorGqlResponse {
  @Field(() => [UserProductReviewListGqlResponse], {
    description: "Product reviews visible to the current END_USER",
  })
  items: UserProductReviewListGqlResponse[];

  @Field(() => PaginationCursorResponse, {
    description: "Pagination metadata",
  })
  pagination: PaginationCursorResponse;

  @Field(() => ProductReviewRatingSummaryGqlResponse, {
    description:
      "Aggregated public rating summary excluding hidden reviews and hidden ratings",
  })
  summary: ProductReviewRatingSummaryGqlResponse;
}
