export const GENERAL_SUBSCRIPTION_UPDATE_TYPES = {
  NOTIFICATION: "NOTIFICATION",
  BADGE_COUNTS: "BADGE_COUNTS",
  VERIFICATION_STATUS: "VERIFICATION_STATUS",
} as const;

export const GENERAL_NOTIFICATION_MESSAGE_TYPES = {
  POPUP: "POPUP",
  SNACKBAR: "SNACKBAR",
} as const;

export type GeneralSubscriptionUpdateType =
  (typeof GENERAL_SUBSCRIPTION_UPDATE_TYPES)[keyof typeof GENERAL_SUBSCRIPTION_UPDATE_TYPES];

export type GeneralNotificationMessageType =
  (typeof GENERAL_NOTIFICATION_MESSAGE_TYPES)[keyof typeof GENERAL_NOTIFICATION_MESSAGE_TYPES];
