export const APP_SETTING_KEY = {
  PAYMENT_CARDS: "PAYMENT_CARDS",
  PAYMENT_METHODS: "PAYMENT_METHODS",
  USDT_WALLETS: "USDT_WALLETS",
  USDT_IRT_RATE: "USDT_IRT_RATE",
  ZARINPAL_CONFIG: "ZARINPAL_CONFIG",
  EMAIL_SMTP_CONFIG: "EMAIL_SMTP_CONFIG",
  EMAIL_TEMPLATES: "EMAIL_TEMPLATES",
  PASSWORD_RESET_TOKEN_TTL_MINUTES: "PASSWORD_RESET_TOKEN_TTL_MINUTES",
  SUPPORT_CONTACT: "SUPPORT_CONTACT",
  APP_ABOUT_PAGE: "APP_ABOUT_PAGE",
  APP_PRIVACY_POLICY_PAGE: "APP_PRIVACY_POLICY_PAGE",
  APP_TERMS_OF_USE_PAGE: "APP_TERMS_OF_USE_PAGE",
  APP_VERSION: "APP_VERSION",
  TICKET_AUTO_CLOSE_AFTER_ANSWERED_HOURS:
    "TICKET_AUTO_CLOSE_AFTER_ANSWERED_HOURS",
  BACKUP_CONFIG: "BACKUP_CONFIG",
  TELEGRAM_CONFIG: "TELEGRAM_CONFIG",
} as const;

/** Settings managed outside the system settings UI. */
export const HIDDEN_APP_SETTING_KEYS = [APP_SETTING_KEY.APP_VERSION] as const;

export const PAYMENT_CHECKOUT_SETTING_KEYS = [
  APP_SETTING_KEY.PAYMENT_CARDS,
  APP_SETTING_KEY.PAYMENT_METHODS,
  APP_SETTING_KEY.USDT_WALLETS,
  APP_SETTING_KEY.USDT_IRT_RATE,
] as const;
