export const USER_FACING_SUCCESS = {
  LOGIN_CODE_SENT: "LOGIN_CODE_SENT",
  SIGNUP_CODE_SENT: "SIGNUP_CODE_SENT",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_SUCCESSFUL: "PASSWORD_RESET_SUCCESSFUL",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  VERIFICATION_EMAIL_SENT: "VERIFICATION_EMAIL_SENT",
} as const;

export type UserFacingSuccessCode =
  (typeof USER_FACING_SUCCESS)[keyof typeof USER_FACING_SUCCESS];
