export enum MediaCompressionSkipReason {
  NONE = "NONE",
  ALREADY_AT_TARGET = "ALREADY_AT_TARGET",
  ALREADY_BELOW_TARGET = "ALREADY_BELOW_TARGET",
  OUTPUT_NOT_SMALLER = "OUTPUT_NOT_SMALLER",
  FILE_TOO_SMALL = "FILE_TOO_SMALL",
}
