export enum UserProductInquiryStatus {
  PREVIEW_GENERATED = "PREVIEW_GENERATED",
  CALL_REQUESTED = "CALL_REQUESTED",
  PENDING = "PENDING",
  CONTACTED = "CONTACTED",
  SALE_COMPLETED = "SALE_COMPLETED",
  CLOSED = "CLOSED",
  CANCELLED = "CANCELLED",
}

export const USER_PRODUCT_INQUIRY_TERMINAL_STATUSES = [
  UserProductInquiryStatus.SALE_COMPLETED,
  UserProductInquiryStatus.CLOSED,
  UserProductInquiryStatus.CANCELLED,
] as const;
