export enum UserProductInquiryStatus {
  PREVIEW_GENERATED = "PREVIEW_GENERATED",
  CALL_REQUESTED = "CALL_REQUESTED",
  PENDING = "PENDING",
  CONTACTED = "CONTACTED",
  SALE_COMPLETED = "SALE_COMPLETED",
  CLOSED = "CLOSED",
  CANCELLED = "CANCELLED",
}
